# AI/ML in Biology & Bioinformatics:
## Section 1: Biological Data Representation, Visualization & Feature Engineering

### 1. Representation & Dimensionality
Biological data is inherently high-dimensional and sparse:
*   **Transcriptomics (RNA-Seq):** Matrices where rows are samples and columns are thousands of gene expression levels ($p \gg n$).
*   **Genomics:** Sequential, categorical strings (A, C, G, T) requiring numeric encoding.

### 2. Feature Engineering Strategies
*   **K-mer Counting:** Breaking sequence data into overlapping substrings of length $k$ to construct frequency vectors.
*   **One-Hot Encoding:** Translating nucleotide or amino acid characters into binary vectors ($A = [1,0,0,0]$). This preserves position but loses context if sequences vary in length.
*   **Physicochemical Descriptors:** Mapping amino acids to physical properties (hydrophobicity, isoelectric point, molecular weight) instead of raw letters.

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

def generate_kmers(sequence, k=3):
    return [sequence[i:i+k] for i in range(len(sequence) - k + 1)]

sequence = "ATCGATCGATTG"
kmers = generate_kmers(sequence, k = 3)
print(f"Generated k-mers(k=3): {kmers}")

amino_acids = np.array(['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L']).reshape(-1, 1)
encoder = OneHotEncoder(sparse_output=False)
encoder.fit(amino_acids)

test_peptide = np.array(['A', 'G', 'C']).reshape(-1, 1)
one_hot_peptide = encoder.transform(test_peptide)
print(f"One-Hot Encoded Peptide (A, G, C): \n{one_hot_peptide}")

Generated k-mers(k=3): ['ATC', 'TCG', 'CGA', 'GAT', 'ATC', 'TCG', 'CGA', 'GAT', 'ATT', 'TTG']
One-Hot Encoded Peptide (A, G, C): 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Section 2: Dimensionality Reduction & Unsupervised Learning

### 1. PCA vs. t-SNE vs. UMAP in Single-Cell RNA-Seq (scRNA-Seq)
*   **PCA (Principal Component Analysis):** Linear reduction. Essential as a preprocessing step to remove noise, but fails to capture complex, non-linear cellular trajectories.
*   **t-SNE / UMAP:** Non-linear graph-based methods. UMAP is heavily preferred in modern bioinformatics because it preserves *global* topology (how distinct cell clusters relate to one another), whereas t-SNE only preserves *local* neighborhoods.

### 2. Clustering Biological Subtypes
*   **Hierarchical Clustering:** Used extensively for generating heatmaps of gene expression Profiles to identify co-expressed gene modules.
*   **K-Means:** Grouping samples into distinct disease subtypes based on biomarker expressions.